#pragma once

#define UINT8_UPPER_LIMIT 0xFF
#define UINT8_LOWER_LIMIT 0
#define UINT16_UPPER_LIMIT 0xFFFF
#define UINT16_LOWER_LIMIT 0
#define UINT32_UPPER_LIMIT 0xFFFF'FFFF
#define UINT32_LOWER_LIMIT 0
#define UINT64_UPPER_LIMIT 0xFFFF'FFFF'FFFF'FFFF
#define UINT64_LOWER_LIMIT 0

#define INT8_UPPER_LIMIT 0x7F
#define INT8_LOWER_LIMIT (-INT8_UPPER_LIMIT - 1)
#define INT16_UPPER_LIMIT 0x7FFF
#define INT16_LOWER_LIMIT (-INT16_UPPER_LIMIT - 1)
#define INT32_UPPER_LIMIT 0x7FFF'FFFF
#define INT32_LOWER_LIMIT (-INT32_UPPER_LIMIT - 1)
#define INT64_UPPER_LIMIT 0x7FFF'FFFF'FFFF'FFFF
#define INT64_LOWER_LIMIT (-INT64_UPPER_LIMIT - 1)
